routes/web.php
    Route::get('ajax/categories-based-on-team', 'AjaxController@getCategoriesBasedOnTeam')->name('get.categories.based.on.team');
    //End Auth ajax requests

    Route::middleware(['auth:web','dashboard'])->group(function (){
        Route::get('index', 'DashboardController@index')->name('index');
        // Charts
        Route::get('charts/offers-analytics', 'DashboardController@chartOffersAnalytics')->name('chart.offers-analytics');
        Route::get('charts/gm-v-po', 'DashboardController@chartGmVPo')->name('chart.gm-v-po');

        Route::resource('users', UserController::class);
        Route::post('users/change/status', 'UserController@changeStatus');
        // User Profile
        Route::get('user/profile', 'UserController@profile')->name('user.profile');

        Route::resource('publishers', PublisherController::class);
        Route::get('publishers/type/{type}', 'PublisherController@getBasedOnType')->name('publishers.type');
        Route::get('publishers-search', 'PublisherController@search')->name('publishers.search');
        Route::post('publishers-update-account-manager', 'PublisherController@updateAccountManager')->name('publishers.updateAccountManager');
        Route::post('publishers-check-exists', 'PublisherController@checkIfExists')->name('publishers.check.exists');
        Route::post('publishers/change/status', 'PublisherController@changeStatus');
        Route::get('publishers/clear/sessions', 'PublisherController@clearFilterSeassoions')->name('publishers.clear.sessions');
        Route::get('publishers/files/download/{dir?}', 'PublisherController@download')->name('publishers.files.download');

        // Publisher Profile
        Route::get('publisher/profile/{id?}', 'PublisherController@profile')->name('publisher.profile');
        Route::get('publisher/payments/{id?}', 'PublisherController@payments')->name('publisher.payments');
        Route::get('publisher/my-account-manager', 'PublisherController@myAccountManager')->name('publisher.account.manager');

        // Upload Publishers
        Route::get('publishers/upload/form', 'PublisherController@upload')->name('publishers.upload.form');
        Route::post('publishers/upload', 'PublisherController@storeUpload')->name('publishers.upload.store');
        Route::get('publishers/import/status', 'PublisherController@importStatus')->name('publishers.import.status');

        // Upload update hasoffer id by email
        Route::get('publishers/upload/update-hasoffer-id-by-email/form', 'PublisherController@uploadUpdateHasOfferIdByEmail')->name('publishers.upload.update.hasoffer.id.by.email.form');
        Route::post('publishers/upload/update-hasoffer-id-by-email', 'PublisherController@storeUploadUpdateHasOfferIdByEmail')->name('publishers.upload.update.hasoffer.id.by.email.store');

        Route::resource('payments', PaymentController::class);
        Route::get('payments/upload/form', 'PaymentController@uploadForm')->name('payments.upload.form');
        Route::post('payments/upload/form', 'PaymentController@upload')->name('payments.upload');
        Route::get('payments/clear/sessions', 'PaymentController@clearFilterSeassoions')->name('payments.clear.sessions');

        Route::resource('roles', RoleController::class);
        Route::resource('cities', CityController::class);
        Route::resource('advertisers', AdvertiserController::class);
        Route::post('advertisers/change/status', 'AdvertiserController@changeStatus');

        Route::resource('categories', CategoryController::class);
        Route::resource('offers', OfferController::class);
        Route::get('my-offers', 'OfferController@myOffers')->name('my-offers');
        Route::get('upload/offers', 'OfferController@upload')->name('upload.offers');
        Route::get('offers/coupons/{offer}', 'OfferController@coupons')->name('offers.coupons');
        Route::get('offers/clear/sessions', 'OfferController@clearFilterSeassoions')->name('offers.clear.sessions');

        Route::resource('offerRequests', OfferRequestController::class);
        Route::get('ajax/offerRequests/form', 'OfferRequestController@offerRequestAjaxForm')->name('offerRequest.ajax.form');
        Route::post('ajax/offerRequests', 'OfferRequestController@offerRequestAjax')->name('offerRequest.ajax');
        Route::post('ajax/offerRequests/coupons', 'OfferRequestController@coupons')->name('offerRequest.ajax.coupons');
        Route::post('ajax/offerRequests/view-coupons', 'OfferRequestController@viewOfferCoupons')->name('offerRequest.ajax.view.coupons');
        Route::get('offerRequests/clear/sessions', 'OfferRequestController@clearFilterSeassoions')->name('offerRequests.clear.sessions');
        Route::post('offerRequests/change/status', 'OfferRequestController@changeStatus');

        Route::post('offers/change/status', 'OfferController@changeStatus');
        Route::get('coupons/bulk-edit', 'CouponController@bulkEdit')->name('coupons.bulk.edit');
        Route::post('coupons/bulk-update', 'CouponController@bulckUpdate')->name('coupons.bulk.update');
        Route::get('coupons/clear/sessions', 'CouponController@clearFilterSeassoions')->name('coupons.clear.sessions');
        Route::get('coupons/files/download/{dir?}', 'CouponController@download')->name('coupons.files.download');

        Route::get('trashed', 'TrashedController@index')->name('trashed.index');
        Route::put('trashed/restore', 'TrashedController@restore')->name('trashed.restore');

        Route::resource('helps', HelpController::class);
        Route::any('helps-upload-image', 'HelpController@uploadImages')->name('helps.image.upload');
        Route::post('helps-search', 'HelpController@search')->name('helps.search');
        // Route::get('help/{slug}', 'HelpController@showBySlug')->name('helps.show.by.slug');

        Route::resource('coupons', CouponController::class);
        Route::resource('reports', PivotReportController::class);
        Route::get('reports/import/status', 'PivotReportController@status')->name('reports.import.status');

        Route::get('reports/clear/sessions', 'PivotReportController@clearFilterSeassoions')->name('reports.clear.sessions');
        //todo
        //        Route::get('publishers/files/download/{dir?}', 'PublisherController@download')->name('publishers.files.download');
        Route::get('reports/download/errors/{dir?}', 'PivotReportController@downLoadErrors')->name('reports.deonload.errore');
        Route::get('reports/define/excel/sheet/columns', 'PivotReportController@defineExcelSheetColumns')->name('define.excel.sheet.columns');
        Route::get('coupons/upload/form', 'CouponController@uploadForm')->name('coupons.upload.form');
        Route::post('coupons/upload','CouponController@upload')->name('coupons.upload');
        Route::get('coupons/upload/status', 'CouponController@importStatus')->name('coupons.upload.status');
        Route::post('coupons/change/status', 'CouponController@changeStatus');
        Route::post('coupons/change/revenue', 'CouponController@bulkChangeRevenue');
        Route::get('coupons/load/payout', 'CouponController@loadPayout');

        // Route::resource('reports', ReportController::class);
        Route::resource('countries', CountryController::class);
        Route::resource('cities', CityController::class);
        Route::resource('targets', TargetController::class);
        // User Activites
        Route::get('user-activities', 'UserActivityController@index')->name('user.activities.index');
        Route::post('user-activities/update-uproval', 'UserActivityController@updateUserActivityApproval')->name('user.activities.update.approval');
        // Chat routes
        Route::get('chat', 'ChatController@index')->name('chat');
        Route::post('chat/message', 'ChatController@messageReceived')->name('chat.message');
        Route::post('chat/single/{user?}', 'ChatController@singleChat')->name('chat.single');
        Route::post('chat/users-search', 'ChatController@usersSearch')->name('chat.users.search');

        Route::group([
            'excluded_middleware' => ['dashboard'],
        ], function () {
            Route::post('logout', 'AuthController@logout')->name('logout');
        });

        // Ajax requests
        Route::post('ajax/cities', 'AjaxController@cities')->name('ajax.cities');
        Route::post('ajax/account-managers', 'AjaxController@accountManagers')->name('ajax.account.managers');
        Route::post('ajax/view-activity-history', 'AjaxController@viewActivityHistory')->name('ajax.view.activity.history');
        Route::post('ajax/read-notification', 'AjaxController@readNotifications')->name('ajax.read.notifications');
        Route::get('ajax/publishers/search', 'AjaxController@publishersSearch')->name('ajax.publishers.search');
        Route::get('ajax/check/jobs', 'AjaxController@checkJobs')->name('ajax.check.jobs');
        // Delete this routes and views
        Route::group(['prefix' => 'publisher'], function(){
            Route::get('dashboard', 'PublisherController@dashboard')->name('publisher.dashboard');
            Route::get('offers', 'PublisherController@offers')->name('publisher.offers');
        });

        Route::group(['prefix' => 'table-handler', 'as' => 'table.handler.'], function(){
            Route::get('set-table-length', 'TableHandlerController@setTableLength')->name('set.table.length');
            Route::get('offers', 'PublisherController@offers')->name('publisher.offers');
        });
    });
});

// Salla Routes
Route::group(['prefix' => 'salla', 'namespace' => 'Dashboard', 'as' => 'salla.'], function(){
    Route::get('install', 'SallaInfoController@installApp');
    Route::view('success', 'admin.salla.install-success')->name('installed.successfully');
    Route::view('failed', 'admin.salla.install-failed')->name('installed.failed');
});

Route::get('login-users', 'Dashboard\DashboardController@loginUsers')->name('login.users')->middleware('auth:web');

app/Models/Advertiser.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Advertiser extends Model
{
    use HasFactory;
    use SoftDeletes;
    protected $guarded = [];
    protected $appends = ['company_name'];

    public function country(){
        return $this->belongsTo(Country::class);
    }

    public function currency(){
        return $this->belongsTo(Currency::class);
    }
    
    public function city(){
        return $this->belongsTo(City::class);
    }

    public function offers(){
        return $this->hasMany(Offer::class);
    }
    
    public function getCompanyNameAttribute(){
        return $this->attributes['company_name_'.app()->getLocale()];
    }

    public function categories(){
        return $this->belongsToMany(Category::class);
    }
}

app/Http/Controllers/Api/AdvertiserController.php
<?php

namespace App\Http\Controllers\Api;

use App\Http\Controllers\Controller;
use App\Http\Resources\AdvertiserResource;
use App\Models\Advertiser;
use Illuminate\Http\Request;

class AdvertiserController extends Controller
{
    public function index(){
        return new AdvertiserResource(Advertiser::all());
    }
}

resources/views/admin/advertisers/index.blade.php
@extends('admin.layouts.app')
@section('title','Advertisers')
@section('content')
    <!--begin::Entry-->
    <div class="d-flex flex-column-fluid">
        <!--begin::Container-->
        <div class="container">
            <!--begin::Card-->
            <div class="card card-custom">
                
                @if(session()->has('message'))
                @include('admin.temps.success')
                @endif
                <div class="card-header flex-wrap border-0 pt-6 pb-0">
                    <div class="card-title">
                        <h3>{{ __('Advertisers') }}</h3>
                    </div>
                    <div class="card-toolbar">
                        <a href="{{route('admin.advertisers.create')}}" class="btn btn-primary font-weight-bolder ">
                            <span class="svg-icon svg-icon-md">
                                <!--begin::Svg Icon | path:assets/media/svg/icons/Design/Flatten.svg-->
                                <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="24px" height="24px" viewBox="0 0 24 24" version="1.1">
                                    <g stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
                                        <rect x="0" y="0" width="24" height="24" />
                                        <circle fill="#000000" cx="9" cy="15" r="6" />
                                        <path d="M8.8012943,7.00241953 C9.83837775,5.20768121 11.7781543,4 14,4 C17.3137085,4 20,6.6862915 20,10 C20,12.2218457 18.7923188,14.1616223 16.9975805,15.1987057 C16.9991904,15.1326658 17,15.0664274 17,15 C17,10.581722 13.418278,7 9,7 C8.93357256,7 8.86733422,7.00080962 8.8012943,7.00241953 Z" fill="#000000" opacity="0.3" />
                                    </g>
                                </svg>
                                <!--end::Svg Icon-->
                            </span> {{ __('Add New Advertiser') }}
                        </a>

                        <!--end::Button-->
                    </div>
                </div>
                <div class="card-body">
                    <!--begin: Search Form-->
                    <!--begin::Search Form-->
                    {{-- <div class="mb-7">
                        <div class="row align-items-center">
                            <div class="col-lg-9 col-xl-8">
                                <div class="row align-items-center">
                                    <div class="col-md-4 my-2 my-md-0">
                                        <div class="input-icon">
                                            <input type="text" class="form-control" placeholder="{{ __('Search...') }}" id="kt_datatable_search_query" />
                                            <span>
																	<i class="flaticon2-search-1 text-muted"></i>
																</span>
                                        </div>
                                    </div>
                                    <div class="col-md-4 my-2 my-md-0">
                                        <div class="d-flex align-items-center">
                                            <label class="mr-3 mb-0 d-none d-md-block">الـحـاله</label>
                                            <select class="form-control" id="kt_datatable_search_status">
                                                <option value="">الجمـيـع</option>
                                                <option value="1">Pending</option>
                                                <option value="2">Delivered</option>
                                                <option value="3">Canceled</option>
                                                <option value="4">Success</option>
                                                <option value="5">Info</option>
                                                <option value="6">Danger</option>
                                            </select>
                                        </div>
                                    </div>
                                    <div class="col-md-4 my-2 my-md-0">
                                        <div class="d-flex align-items-center">
                                            <label class="mr-3 mb-0 d-none d-md-block">الـنـوع:</label>
                                            <select class="form-control" id="kt_datatable_search_type">
                                                <option value="">الجمـيـع</option>
                                                <option value="1">Online</option>
                                                <option value="2">Retail</option>
                                                <option value="3">Direct</option>
                                            </select>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="col-lg-3 col-xl-4 mt-5 mt-lg-0">
                                <a href="#" class="btn btn-light-primary px-6 font-weight-bold">بــحــث</a>
                            </div>
                        </div>
                    </div> --}}
                    <!--end::Search Form-->
                    <!--end: Search Form-->
                    <!--begin: Datatable-->
                    <div class="datatable datatable-bordered datatable-head-custom" id="kt_datatable"></div>
                    <!--end: Datatable-->
                </div>
            </div>
            <!--end::Card-->
        </div>
        <!--end::Container-->
    </div>
    <!--end::Entry-->
@endsection
@push('scripts')
<script>
    var route = "{{ route('admin.advertisers.index') }}";
</script>

<script src="{{asset('js/datatables/advertisers2.js')}}"></script>
@endpush