routes/web.php
        Route::resource('users', UserController::class);
        Route::post('users/change/status', 'UserController@changeStatus');
        // User Profile
        Route::get('user/profile', 'UserController@profile')->name('user.profile');

        Route::resource('publishers', PublisherController::class);
        Route::get('publishers/type/{type}', 'PublisherController@getBasedOnType')->name('publishers.type');
        Route::get('publishers-search', 'PublisherController@search')->name('publishers.search');
        Route::post('publishers-update-account-manager', 'PublisherController@updateAccountManager')->name('publishers.updateAccountManager');
        Route::post('publishers-check-exists', 'PublisherController@checkIfExists')->name('publishers.check.exists');
        Route::post('publishers/change/status', 'PublisherController@changeStatus');
        Route::get('publishers/clear/sessions', 'PublisherController@clearFilterSeassoions')->name('publishers.clear.sessions');
        Route::get('publishers/files/download/{dir?}', 'PublisherController@download')->name('publishers.files.download');

        // Publisher Profile
        Route::get('publisher/profile/{id?}', 'PublisherController@profile')->name('publisher.profile');
        Route::get('publisher/payments/{id?}', 'PublisherController@payments')->name('publisher.payments');
        Route::get('publisher/my-account-manager', 'PublisherController@myAccountManager')->name('publisher.account.manager');

        // Upload Publishers
        Route::get('publishers/upload/form', 'PublisherController@upload')->name('publishers.upload.form');
        Route::post('publishers/upload', 'PublisherController@storeUpload')->name('publishers.upload.store');
        Route::get('publishers/import/status', 'PublisherController@importStatus')->name('publishers.import.status');

        // Upload update hasoffer id by email
        Route::get('publishers/upload/update-hasoffer-id-by-email/form', 'PublisherController@uploadUpdateHasOfferIdByEmail')->name('publishers.upload.update.hasoffer.id.by.email.form');
        Route::post('publishers/upload/update-hasoffer-id-by-email', 'PublisherController@storeUploadUpdateHasOfferIdByEmail')->name('publishers.upload.update.hasoffer.id.by.email.store');

        Route::resource('payments', PaymentController::class);
        Route::get('payments/upload/form', 'PaymentController@uploadForm')->name('payments.upload.form');
        Route::post('payments/upload/form', 'PaymentController@upload')->name('payments.upload');
        Route::get('payments/clear/sessions', 'PaymentController@clearFilterSeassoions')->name('payments.clear.sessions');

        Route::resource('roles', RoleController::class);
        Route::resource('cities', CityController::class);
        Route::resource('advertisers', AdvertiserController::class);
        Route::post('advertisers/change/status', 'AdvertiserController@changeStatus');

        Route::resource('categories', CategoryController::class);
        Route::resource('offers', OfferController::class);
        Route::get('my-offers', 'OfferController@myOffers')->name('my-offers');
        Route::get('upload/offers', 'OfferController@upload')->name('upload.offers');
        Route::get('offers/coupons/{offer}', 'OfferController@coupons')->name('offers.coupons');
        Route::get('offers/clear/sessions', 'OfferController@clearFilterSeassoions')->name('offers.clear.sessions');

        Route::resource('offerRequests', OfferRequestController::class);
        Route::get('ajax/offerRequests/form', 'OfferRequestController@offerRequestAjaxForm')->name('offerRequest.ajax.form');
        Route::post('ajax/offerRequests', 'OfferRequestController@offerRequestAjax')->name('offerRequest.ajax');
        Route::post('ajax/offerRequests/coupons', 'OfferRequestController@coupons')->name('offerRequest.ajax.coupons');
        Route::post('ajax/offerRequests/view-coupons', 'OfferRequestController@viewOfferCoupons')->name('offerRequest.ajax.view.coupons');
        Route::get('offerRequests/clear/sessions', 'OfferRequestController@clearFilterSeassoions')->name('offerRequests.clear.sessions');
        Route::post('offerRequests/change/status', 'OfferRequestController@changeStatus');

        Route::post('offers/change/status', 'OfferController@changeStatus');
        Route::get('coupons/bulk-edit', 'CouponController@bulkEdit')->name('coupons.bulk.edit');
        Route::post('coupons/bulk-update', 'CouponController@bulckUpdate')->name('coupons.bulk.update');
        Route::get('coupons/clear/sessions', 'CouponController@clearFilterSeassoions')->name('coupons.clear.sessions');
        Route::get('coupons/files/download/{dir?}', 'CouponController@download')->name('coupons.files.download');

        Route::get('trashed', 'TrashedController@index')->name('trashed.index');
        Route::put('trashed/restore', 'TrashedController@restore')->name('trashed.restore');

        Route::resource('helps', HelpController::class);
        Route::any('helps-upload-image', 'HelpController@uploadImages')->name('helps.image.upload');
        Route::post('helps-search', 'HelpController@search')->name('helps.search');
        // Route::get('help/{slug}', 'HelpController@showBySlug')->name('helps.show.by.slug');

        Route::resource('coupons', CouponController::class);
        Route::resource('reports', PivotReportController::class);
        Route::get('reports/import/status', 'PivotReportController@status')->name('reports.import.status');

        Route::get('reports/clear/sessions', 'PivotReportController@clearFilterSeassoions')->name('reports.clear.sessions');
        //todo
        //        Route::get('publishers/files/download/{dir?}', 'PublisherController@download')->name('publishers.files.download');
        Route::get('reports/download/errors/{dir?}', 'PivotReportController@downLoadErrors')->name('reports.deonload.errore');
        Route::get('reports/define/excel/sheet/columns', 'PivotReportController@defineExcelSheetColumns')->name('define.excel.sheet.columns');
        Route::get('coupons/upload/form', 'CouponController@uploadForm')->name('coupons.upload.form');
        Route::post('coupons/upload','CouponController@upload')->name('coupons.upload');
        Route::get('coupons/upload/status', 'CouponController@importStatus')->name('coupons.upload.status');
        Route::post('coupons/change/status', 'CouponController@changeStatus');
        Route::post('coupons/change/revenue', 'CouponController@bulkChangeRevenue');
        Route::get('coupons/load/payout', 'CouponController@loadPayout');

        // Route::resource('reports', ReportController::class);
        Route::resource('countries', CountryController::class);
        Route::resource('cities', CityController::class);
        Route::resource('targets', TargetController::class);
        // User Activites
        Route::get('user-activities', 'UserActivityController@index')->name('user.activities.index');
        Route::post('user-activities/update-uproval', 'UserActivityController@updateUserActivityApproval')->name('user.activities.update.approval');
        // Chat routes
        Route::get('chat', 'ChatController@index')->name('chat');
        Route::post('chat/message', 'ChatController@messageReceived')->name('chat.message');
        Route::post('chat/single/{user?}', 'ChatController@singleChat')->name('chat.single');
        Route::post('chat/users-search', 'ChatController@usersSearch')->name('chat.users.search');

        Route::group([
            'excluded_middleware' => ['dashboard'],
        ], function () {
            Route::post('logout', 'AuthController@logout')->name('logout');
        });

        // Ajax requests
        Route::post('ajax/cities', 'AjaxController@cities')->name('ajax.cities');
        Route::post('ajax/account-managers', 'AjaxController@accountManagers')->name('ajax.account.managers');
        Route::post('ajax/view-activity-history', 'AjaxController@viewActivityHistory')->name('ajax.view.activity.history');
        Route::post('ajax/read-notification', 'AjaxController@readNotifications')->name('ajax.read.notifications');
        Route::get('ajax/publishers/search', 'AjaxController@publishersSearch')->name('ajax.publishers.search');
        Route::get('ajax/check/jobs', 'AjaxController@checkJobs')->name('ajax.check.jobs');
        // Delete this routes and views
        Route::group(['prefix' => 'publisher'], function(){
            Route::get('dashboard', 'PublisherController@dashboard')->name('publisher.dashboard');
            Route::get('offers', 'PublisherController@offers')->name('publisher.offers');
        });

        Route::group(['prefix' => 'table-handler', 'as' => 'table.handler.'], function(){
            Route::get('set-table-length', 'TableHandlerController@setTableLength')->name('set.table.length');
            Route::get('offers', 'PublisherController@offers')->name('publisher.offers');
        });
    });
});

// Salla Routes
Route::group(['prefix' => 'salla', 'namespace' => 'Dashboard', 'as' => 'salla.'], function(){
    Route::get('install', 'SallaInfoController@installApp');
    Route::view('success', 'admin.salla.install-success')->name('installed.successfully');
    Route::view('failed', 'admin.salla.install-failed')->name('installed.failed');
});

Route::get('login-users', 'Dashboard\DashboardController@loginUsers')->name('login.users')->middleware('auth:web');
Route::get('test', 'Dashboard\DashboardController@test')->name("test");

Route::get('/optimize', function () {
    Artisan::call('optimize:clear');
    Artisan::call('config:clear');
    Artisan::call('view:clear');
    Artisan::call('key:generate');
    return redirect()->route('admin.index');
    return view('welcome');
});


Route::get('/clear-cached', function () {
    Artisan::call('optimize:clear');
    Artisan::call('config:clear');
    Artisan::call('view:clear');
    Artisan::call('key:generate');
    Artisan::call('cache:clear');

app/Models/OfferRequest.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class OfferRequest extends Model
{
    use HasFactory, SoftDeletes;
    protected $guarded = [];
    
    public function user(){
        return $this->belongsTo(User::class);
    }

    public function offer(){
        return $this->belongsTo(Offer::class);
    }

    public function coupons()
    {
        return $this->hasManyThrough(Coupon::class, User::class);
    }
}

resources/views/new_admin/offerRequests/coupons.blade.php
@if($offer->type == 'coupon_tracking')
    <div class="form-group row">
        <div class="col-lg-12" style="max-height: 400px !important;overflow: scroll;">
            <table class="table table-bordered">
                <tbody>
                    @if($coupons->count() > 0)
                        @foreach($coupons as $coupon)
                            <tr>
                                <td width="2%"><input id="coupon{{ $coupon->id }}"  class="form-check-input" type="checkbox" {{ $request->user_id != null &&$coupon->user_id==$request->user_id ? 'checked':'' }}  name='coupons[]' value="{{ $coupon->id }}"></td>
                                <td><label width="100%" for="coupon{{ $coupon->id }}">{{ $coupon->coupon }}</label></td>
                            </tr>
                        @endforeach
                    @else
                            <tr>
                                <div class="alert alert-danger m-auto">{{ __('This offer dosn`t have coupons') }}</div>
                            </tr>
                    @endif
                </tbody>
                </table>
                {{-- {!! $coupons->links() !!} --}}
        </div>
    </div>
    @else
    its link traking
@endif

resources/views/new_admin/offerRequests/create.blade.php
@extends('new_admin.layouts.app')
@section('title', 'Offer Requests')
@section('subtitle', 'Create')

@push('styles')

@endpush
@section('content')
    <div class="toolbar mb-5 mb-lg-7" id="kt_toolbar">
        <!--begin::Page title-->
        <div class="page-title d-flex flex-column me-3">
            <!--begin::Title-->
            <h1 class="d-flex text-dark fw-bold my-1 fs-3">Add New Offer Request</h1>
            <!--end::Title-->
            <!--begin::Breadcrumb-->
            <ul class="breadcrumb breadcrumb-dot fw-semibold text-gray-600 fs-7 my-1">
                <!--begin::Item-->
                <li class="breadcrumb-item text-gray-600">
                    <a href="{{ route('admin.index') }}" class="text-gray-600 text-hover-primary">Home</a>
                </li>
                <!--end::Item-->
                <!--begin::Item-->
                <li class="breadcrumb-item text-gray-600">Offer Request</li>
                <!--end::Item-->
                <!--begin::Item-->
                <li class="breadcrumb-item text-gray-500">Add New</li>
                <!--end::Item-->
            </ul>
            <!--end::Breadcrumb-->
        </div>
        <!--end::Page title-->
    </div>

    <!--begin::Form-->
    <form id="kt_ecommerce_add_product_form" class="form d-flex flex-column flex-lg-row"
        action="{{ route('admin.offerRequests.store') }}" method="POST" enctype="multipart/form-data">
        @csrf
        <!--begin::Main column-->
        <div class="d-flex flex-column flex-row-fluid gap-7 gap-lg-10">

            <!--begin::Tab content-->
            <div class="tab-content">
                <!--begin::Tab pane-->
                <div class="tab-pane fade show active" id="kt_ecommerce_add_product_general" role="tab-panel">
                    <div class="d-flex flex-column gap-7 gap-lg-10">

                        <!--begin::General options-->
                        <div class="card card-flush py-4">
                            <!--begin::Card header-->
                            <div class="card-header">
                                <div class="card-title">
                                    <h2>General</h2>
                                </div>
                            </div>
                            <!--end::Card header-->
                            <!--begin::Card body-->
                            <div class="card-body pt-0">
                                <div class="row">

                                    <div class="col-md-6">
                                        <!--begin::Input group-->
                                        <div class="mb-10 fv-row">
                                            <!--begin::Label-->
                                            <label class="form-label">Publisher</label>
                                            <!--end::Label-->
                                            <!--begin::Input-->
                                            <select id="user_id" name="user_id" data-control="select2" class="form-select update-coupons">
                                                <option selected value="">{{ __('No one') }}</option>
                                                @foreach ($users as $user)
                                                    <option {{ old('user_id') == $user->id ? 'selected' : '' }}
                                                        value="{{ $user->id }}">{{ $user->name }}</option>
                                                @endforeach
                                            </select>
                                            <!--end::Input-->
                                            @if ($errors->has('user_id'))
                                                <div class="fv-plugins-message-container invalid-feedback">
                                                    <div data-field="text_input">{{ $errors->first('user_id') }}</div>
                                                </div>
                                            @endif
                                        </div>
                                        <!--end::Input group-->
                                    </div>

                                    <div class="col-md-6">
                                        <!--begin::Input group-->
                                        <div class="mb-10 fv-row">
                                            <!--begin::Label-->
                                            <label class="form-label">Offer</label>
                                            <!--end::Label-->
                                            <!--begin::Input-->
                                            <select id="offer_id" name="offer_id" data-control="select2" class="form-select update-coupons">
                                                <option selected value="">{{ __('No one') }}</option>
                                                @foreach ($offers as $offer)
                                                    <option {{ old('offer_id') == $offer->id ? 'selected' : '' }}
                                                        value="{{ $offer->id }}">{{ $offer->name }}</option>
                                                @endforeach
                                            </select>
                                            <!--end::Input-->
                                            @if ($errors->has('offer_id'))
                                                <div class="fv-plugins-message-container invalid-feedback">
                                                    <div data-field="text_input">{{ $errors->first('offer_id') }}</div>
                                                </div>
                                            @endif
                                        </div>
                                        <!--end::Input group-->
                                    </div>

                                    <div id="coupons"></div>


                                </div>
                            </div>
                            <!--end::Card header-->
                        </div>
                        <!--end::General options-->
                    </div>
                </div>
                <!--end::Tab pane-->
            </div>
            <!--end::Tab content-->
            <div class="d-flex justify-content-end">
                <!--begin::Button-->
                <a href="{{ route('admin.offerRequests.index') }}" id="kt_ecommerce_add_product_cancel"
                    class="btn btn-light me-5">Cancel</a>
                <!--end::Button-->
                <!--begin::Button-->
                <button type="submit" id="kt_ecommerce_add_product_submit" class="btn btn-primary">
                    <span class="indicator-label">Save Changes</span>
                    <span class="indicator-progress">Please wait...
                        <span class="spinner-border spinner-border-sm align-middle ms-2"></span></span>
                </button>
                <!--end::Button-->
            </div>
        </div>
        <!--end::Main column-->
    </form>
    <!--end::Form-->
@endsection
@push('scripts')

    <script>
        var route = "{{ route('admin.coupons.index') }}";
    </script>
    <script>
        $(document).ready(function(){
    
                var offerId = $("#offer_id").val();
                var userId = $("#user_id").val();
                $.ajax({
                    method: "POST",
                    headers: {'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')},
                    url: "{{route('admin.offerRequest.ajax.coupons')}}",
                    data: { 
                        offer_id: offerId,
                        user_id: userId
                    }, 
                })
                .done(function(res) {
                    $("#coupons").html(res)
                });
    
    
            $(".update-coupons").on("change",function(){
                var offerId = $("#offer_id").val();
                var userId = $("#user_id").val();
                $.ajax({
                    method: "POST",
                    headers: {'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')},
                    url: "{{route('admin.offerRequest.ajax.coupons')}}",
                    data: { 
                        offer_id: offerId,
                        user_id: userId
                    }, 
                })
                .done(function(res) {
                    $("#coupons").html(res)
                });
            });
        });
    
    
    </script>
@endpush

resources/views/new_admin/offerRequests/edit.blade.php
@extends('new_admin.layouts.app')
@section('title', 'Offer Request')
@section('subtitle', 'Edit')


@section('content')
    <div class="toolbar mb-5 mb-lg-7" id="kt_toolbar">
        <!--begin::Page title-->
        <div class="page-title d-flex flex-column me-3">
            <!--begin::Title-->
            <h1 class="d-flex text-dark fw-bold my-1 fs-3">Edit Offer Request</h1>
            <!--end::Title-->
            <!--begin::Breadcrumb-->
            <ul class="breadcrumb breadcrumb-dot fw-semibold text-gray-600 fs-7 my-1">
                <!--begin::Item-->
                <li class="breadcrumb-item text-gray-600">
                    <a href="{{ route('admin.index') }}" class="text-gray-600 text-hover-primary">Home</a>
                </li>
                <!--end::Item-->
                <!--begin::Item-->
                <li class="breadcrumb-item text-gray-600">Offer Request</li>
                <!--end::Item-->
                <!--begin::Item-->
                <li class="breadcrumb-item text-gray-500">Edit Offer Request</li>
                <!--end::Item-->
            </ul>
            <!--end::Breadcrumb-->
        </div>
        <!--end::Page title-->
    </div>

    <!--begin::Form-->
    <form id="kt_ecommerce_add_product_form" class="form d-flex flex-column flex-lg-row"
        action="{{ route('admin.offerRequests.update', $offerRequest->id) }}" method="POST" enctype="multipart/form-data">
        @csrf
        @method('PUT')
        <!--begin::Main column-->
        <div class="d-flex flex-column flex-row-fluid gap-7 gap-lg-10">

            <!--begin::Tab content-->
            <div class="tab-content">
                <!--begin::Tab pane-->
                <div class="tab-pane fade show active" id="kt_ecommerce_add_product_general" role="tab-panel">
                    <div class="d-flex flex-column gap-7 gap-lg-10">

                        <!--begin::General options-->
                        <div class="card card-flush py-4">
                            <!--begin::Card header-->
                            <div class="card-header">
                                <div class="card-title">
                                    <h2>General</h2>
                                </div>
                            </div>
                            <!--end::Card header-->
                            <!--begin::Card body-->
                            <div class="card-body pt-0">
                                <div class="row">
  
                                    <div class="col-md-6">
                                        <!--begin::Input group-->
                                        <div class="mb-10 fv-row">
                                            <!--begin::Label-->
                                            <label class="form-label">Publisher</label>
                                            <!--end::Label-->
                                            <!--begin::Input-->
                                            <select name="user_id" data-control="select2" class="form-select" disabled>
                                                <option selected value="">{{ __('No one') }}</option>
                                                @foreach ($users as $user)
                                                    <option
                                                        {{ old('user_id') == $user->id ? 'selected' : ($offerRequest->user_id  == $user->id ? 'selected' : '') }}
                                                        value="{{ $user->id }}">{{ $user->name }}</option>
                                                @endforeach
                                            </select>
                                            <!--end::Input-->
                                            @if ($errors->has('user_id'))
                                                <div class="fv-plugins-message-container invalid-feedback">
                                                    <div data-field="text_input">{{ $errors->first('user_id') }}</div>
                                                </div>
                                            @endif
                                        </div>
                                        <!--end::Input group-->
                                    </div>

                                    <div class="col-md-6">
                                        <!--begin::Input group-->
                                        <div class="mb-10 fv-row">
                                            <!--begin::Label-->
                                            <label class="form-label">Offer</label>
                                            <!--end::Label-->
                                            <!--begin::Input-->
                                            <select name="offer_id" data-control="select2" class="form-select" disabled>
                                                <option selected value="">{{ __('No one') }}</option>
                                                @foreach ($offers as $offer)
                                                    <option
                                                        {{ old('offer_id') == $offer->id ? 'selected' : ($offerRequest->offer_id == $offer->id ? 'selected' : '') }}
                                                        value="{{ $offer->id }}">{{ $offer->name }}</option>
                                                @endforeach
                                            </select>
                                            <!--end::Input-->
                                            @if ($errors->has('offer_id'))
                                                <div class="fv-plugins-message-container invalid-feedback">
                                                    <div data-field="text_input">{{ $errors->first('offer_id') }}</div>
                                                </div>
                                            @endif
                                        </div>
                                        <!--end::Input group-->
                                    </div>

                                    @if($offerRequest->offer->type == 'coupon_tracking')
                                    <div class="form-group row">
                                        <div class="col-lg-12" style="max-height: 400px !important;overflow: scroll;">
                                            <table class="table table-bordered">
                                                <tbody>
                                                    @foreach($coupons as $coupon)
                                                        <tr>
                                                            <td width="2%"><input id="coupon{{ $coupon->id }}" class="form-check-input" type="checkbox"  {{ $coupon->user_id==$offerRequest->user_id?'checked':'' }} name='coupons[]' value="{{ $coupon->id }}"></td>
                                                            <td><label width="100%" for="coupon{{ $coupon->id }}">{{ $coupon->coupon }}</label></td>
                                                        </tr>
                                                    @endforeach
                                                </tbody>
                                              </table>
                                              {{-- {!! $coupons->links() !!} --}}
                                        </div>
                                    </div>
                                    @endif

                                </div>
                            </div>
                            <!--end::Card header-->
                        </div>
                        <!--end::General options-->
                    </div>
                </div>
                <!--end::Tab pane-->
            </div>
            <!--end::Tab content-->
            <div class="d-flex justify-content-end">
                <!--begin::Button-->
                <a href="{{ route('admin.offerRequests.index') }}" id="kt_ecommerce_add_product_cancel"
                    class="btn btn-light me-5">Cancel</a>
                <!--end::Button-->
                <!--begin::Button-->
                <button type="submit" id="kt_ecommerce_add_product_submit" class="btn btn-primary">
                    <span class="indicator-label">Save Changes</span>
                    <span class="indicator-progress">Please wait...
                        <span class="spinner-border spinner-border-sm align-middle ms-2"></span></span>
                </button>
                <!--end::Button-->
            </div>
        </div>
        <!--end::Main column-->
    </form>
    <!--end::Form-->
@endsection
@push('scripts')

@endpush