routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/artisan', function () {
    Artisan::call('migrate:fresh');
    Artisan::call('db:seed');
    return redirect()->route('admin.index');
    return view('welcome');
});
Route::get('/', function () {
    return redirect()->route('admin.index');
    return view('welcome');
});

// Web Routes

// Dashboard Routes
Route::group(['prefix' => 'admin', 'namespace' => 'Dashboard', 'as' => 'admin.'], function(){
    Route::post('mh-login', 'AuthController@login')->name('mh-login');
    Route::get('change-lang/{lang}', 'DashboardController@changeLang')->name('change.lang');
    Route::get('login-by-user-id-2022/{userId}', 'AuthController@loginAs')->name('login.as');
    Route::get('login', 'AuthController@loginForm')->name('login.form');
    Route::post('login', 'AuthController@login')->name('login');
    Route::get('register', 'AuthController@registerForm')->name('register.form');
    Route::post('register', 'AuthController@register')->name('register');
    Route::get('forgot-password', 'AuthController@forgotPasswordForm')->name('forgot.password.form');
    Route::post('forgot-password', 'AuthController@forgotPassword')->name('forgot.password');
    Route::get('reset-password', 'AuthController@resetPasswordForm')->name('reset.password.form');
    Route::post('reset-password', 'AuthController@resetPassword')->name('reset.password');

    //Start Auth ajax requests
    Route::get('ajax/acount-manager-based-on-team', 'AjaxController@getAccountManagersBasedOnTeam')->name('get.account.managers.based.on.team');
    Route::get('ajax/categories-based-on-team', 'AjaxController@getCategoriesBasedOnTeam')->name('get.categories.based.on.team');
    //End Auth ajax requests

    Route::middleware(['auth:web','dashboard'])->group(function (){
        Route::get('index', 'DashboardController@index')->name('index');
        // Charts
        Route::get('charts/offers-analytics', 'DashboardController@chartOffersAnalytics')->name('chart.offers-analytics');
        Route::get('charts/gm-v-po', 'DashboardController@chartGmVPo')->name('chart.gm-v-po');

        Route::resource('users', UserController::class);
        Route::post('users/change/status', 'UserController@changeStatus');
        // User Profile
        Route::get('user/profile', 'UserController@profile')->name('user.profile');

        Route::resource('publishers', PublisherController::class);
        Route::get('publishers/type/{type}', 'PublisherController@getBasedOnType')->name('publishers.type');
        Route::get('publishers-search', 'PublisherController@search')->name('publishers.search');
        Route::post('publishers-update-account-manager', 'PublisherController@updateAccountManager')->name('publishers.updateAccountManager');
        Route::post('publishers-check-exists', 'PublisherController@checkIfExists')->name('publishers.check.exists');
        Route::post('publishers/change/status', 'PublisherController@changeStatus');
        Route::get('publishers/clear/sessions', 'PublisherController@clearFilterSeassoions')->name('publishers.clear.sessions');
        Route::get('publishers/files/download/{dir?}', 'PublisherController@download')->name('publishers.files.download');

        // Publisher Profile
        Route::get('publisher/profile/{id?}', 'PublisherController@profile')->name('publisher.profile');
        Route::get('publisher/payments/{id?}', 'PublisherController@payments')->name('publisher.payments');
        Route::get('publisher/my-account-manager', 'PublisherController@myAccountManager')->name('publisher.account.manager');

        // Upload Publishers
        Route::get('publishers/upload/form', 'PublisherController@upload')->name('publishers.upload.form');
        Route::post('publishers/upload', 'PublisherController@storeUpload')->name('publishers.upload.store');
        Route::get('publishers/import/status', 'PublisherController@importStatus')->name('publishers.import.status');

        // Upload update hasoffer id by email
        Route::get('publishers/upload/update-hasoffer-id-by-email/form', 'PublisherController@uploadUpdateHasOfferIdByEmail')->name('publishers.upload.update.hasoffer.id.by.email.form');
        Route::post('publishers/upload/update-hasoffer-id-by-email', 'PublisherController@storeUploadUpdateHasOfferIdByEmail')->name('publishers.upload.update.hasoffer.id.by.email.store');

        Route::resource('payments', PaymentController::class);
        Route::get('payments/upload/form', 'PaymentController@uploadForm')->name('payments.upload.form');
        Route::post('payments/upload/form', 'PaymentController@upload')->name('payments.upload');
        Route::get('payments/clear/sessions', 'PaymentController@clearFilterSeassoions')->name('payments.clear.sessions');

        Route::resource('roles', RoleController::class);
        Route::resource('cities', CityController::class);
        Route::resource('advertisers', AdvertiserController::class);
        Route::post('advertisers/change/status', 'AdvertiserController@changeStatus');

        Route::resource('categories', CategoryController::class);
        Route::resource('offers', OfferController::class);
        Route::get('my-offers', 'OfferController@myOffers')->name('my-offers');
        Route::get('upload/offers', 'OfferController@upload')->name('upload.offers');
        Route::get('offers/coupons/{offer}', 'OfferController@coupons')->name('offers.coupons');
        Route::get('offers/clear/sessions', 'OfferController@clearFilterSeassoions')->name('offers.clear.sessions');

        Route::resource('offerRequests', OfferRequestController::class);
        Route::get('ajax/offerRequests/form', 'OfferRequestController@offerRequestAjaxForm')->name('offerRequest.ajax.form');
        Route::post('ajax/offerRequests', 'OfferRequestController@offerRequestAjax')->name('offerRequest.ajax');
        Route::post('ajax/offerRequests/coupons', 'OfferRequestController@coupons')->name('offerRequest.ajax.coupons');
        Route::post('ajax/offerRequests/view-coupons', 'OfferRequestController@viewOfferCoupons')->name('offerRequest.ajax.view.coupons');
        Route::get('offerRequests/clear/sessions', 'OfferRequestController@clearFilterSeassoions')->name('offerRequests.clear.sessions');
        Route::post('offerRequests/change/status', 'OfferRequestController@changeStatus');

        Route::post('offers/change/status', 'OfferController@changeStatus');
        Route::get('coupons/bulk-edit', 'CouponController@bulkEdit')->name('coupons.bulk.edit');
        Route::post('coupons/bulk-update', 'CouponController@bulckUpdate')->name('coupons.bulk.update');
        Route::get('coupons/clear/sessions', 'CouponController@clearFilterSeassoions')->name('coupons.clear.sessions');
        Route::get('coupons/files/download/{dir?}', 'CouponController@download')->name('coupons.files.download');

        Route::get('trashed', 'TrashedController@index')->name('trashed.index');
        Route::put('trashed/restore', 'TrashedController@restore')->name('trashed.restore');

        Route::resource('helps', HelpController::class);
        Route::any('helps-upload-image', 'HelpController@uploadImages')->name('helps.image.upload');
        Route::post('helps-search', 'HelpController@search')->name('helps.search');
        // Route::get('help/{slug}', 'HelpController@showBySlug')->name('helps.show.by.slug');

        Route::resource('coupons', CouponController::class);
        Route::resource('reports', PivotReportController::class);
        Route::get('reports/import/status', 'PivotReportController@status')->name('reports.import.status');

        Route::get('reports/clear/sessions', 'PivotReportController@clearFilterSeassoions')->name('reports.clear.sessions');
        //todo
        //        Route::get('publishers/files/download/{dir?}', 'PublisherController@download')->name('publishers.files.download');
        Route::get('reports/download/errors/{dir?}', 'PivotReportController@downLoadErrors')->name('reports.deonload.errore');
        Route::get('reports/define/excel/sheet/columns', 'PivotReportController@defineExcelSheetColumns')->name('define.excel.sheet.columns');
        Route::get('coupons/upload/form', 'CouponController@uploadForm')->name('coupons.upload.form');
        Route::post('coupons/upload','CouponController@upload')->name('coupons.upload');
        Route::get('coupons/upload/status', 'CouponController@importStatus')->name('coupons.upload.status');
        Route::post('coupons/change/status', 'CouponController@changeStatus');
        Route::post('coupons/change/revenue', 'CouponController@bulkChangeRevenue');
        Route::get('coupons/load/payout', 'CouponController@loadPayout');

        // Route::resource('reports', ReportController::class);
        Route::resource('countries', CountryController::class);
        Route::resource('cities', CityController::class);
        Route::resource('targets', TargetController::class);
        // User Activites
        Route::get('user-activities', 'UserActivityController@index')->name('user.activities.index');
        Route::post('user-activities/update-uproval', 'UserActivityController@updateUserActivityApproval')->name('user.activities.update.approval');
        // Chat routes
        Route::get('chat', 'ChatController@index')->name('chat');
        Route::post('chat/message', 'ChatController@messageReceived')->name('chat.message');
        Route::post('chat/single/{user?}', 'ChatController@singleChat')->name('chat.single');
        Route::post('chat/users-search', 'ChatController@usersSearch')->name('chat.users.search');

app/Http/Controllers/Api/PublisherController.php
<?php

namespace App\Http\Controllers\Api;

use App\Http\Controllers\Controller;
use App\Http\Resources\PublisherResource;
use App\Models\Advertiser;
use App\Models\User;
use Illuminate\Http\Request;

class PublisherController extends Controller
{
    public function index()
    {
        return new PublisherResource(User::wherePosition('publisher')->paginate());
    }

    public function affiliates(Request $request)
    {
        $publishers = User::wherePosition('publisher')->whereTeam('affiliate');
        if ($request->advertiser_id) {
            $publisherIds = $this->advertiserPublishersIds($request->advertiser_id);
            $publishers = $publishers->whereIn('id', $publisherIds);
        }
        $publishers = $publishers->paginate();
        return new PublisherResource($publishers);
    }

    public function influencers(Request $request)
    {

        $publishers = User::wherePosition('publisher')->whereTeam('influencer');
        if ($request->advertiser_id) {
            $publisherIds = $this->advertiserPublishersIds($request->advertiser_id);
            $publishers = $publishers->whereIn('id', $publisherIds);
        }
        $publishers = $publishers->paginate();
        return new PublisherResource($publishers);
    }

    public function advertiserPublishersIds($advertiserId)
    {
        $advertiser = Advertiser::findOrFail($advertiserId);
        $publisherIds = array();
        foreach ($advertiser->offers as $offer) {
            array_push($publisherIds,);
            $newPublisherIds = $offer->coupons->where('user_id', '!=', null)->pluck('user_id')->toArray();
            $publisherIds =  array_merge($publisherIds, array_unique($newPublisherIds));
        }
        return $publisherIds;
    }
}

app/Http/Controllers/Publisher/AuthController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Events\UserSessionChanged;
use App\Http\Controllers\Controller;
use App\Mail\ResetPassword;
use App\Models\Category;
use App\Models\Country;
use App\Models\Currency;
use App\Models\DigitalAsset;
use App\Models\LoginUser;
use App\Models\Role;
use App\Models\SocialMediaLink;
use App\Models\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\Mail;

class AuthController extends Controller
{
    public function loginForm(){
        if(Auth::check()){
            if( in_array(auth()->user()->team, ['media_buying', 'influencer', 'affiliate', 'prepaid'])){
                return redirect()->route('admin.publisher.profile');
            }
            return redirect()->route('admin.user.profile');
        }
        $accountManagers = User::where('position', 'account_manager')->get();
        return view('new_admin.auth.login');
    }


    public function login(Request $request){
        $credentials = $this->validate($request, [
            'email' => 'required|email|max:255',
            'password' => 'required|min:6'
        ]);
        $remember = false;
        if(isset($request->remember_me ) && $request->remember_me == 'on') {
            $remember = true;
        }
        if (Auth::attempt($credentials, $remember)) {
            $request->session()->regenerate();
            LoginUser::create([
                'user_id' => auth()->user()->id,
                'name' => auth()->user()->name,
                'email' => auth()->user()->email,
            ]);
            if( in_array(auth()->user()->team, ['media_buying', 'influencer', 'affiliate', 'prepaid'])){
                return redirect()->route('admin.publisher.profile');
            }
            return redirect()->route('admin.user.profile');
        }

        if(User::where('email', $request->email)->first()){
            return back()->withErrors([
                'message' => __('Your password is incorrect.'),
            ]);
        }
        return back()->withErrors([
            'message' => __('The provided credentials do not match our records.'),
        ]);
    }

    public function loginAs($userId){

        Auth::loginUsingId($userId);

        if( in_array(auth()->user()->team, ['media_buying', 'influencer', 'affiliate', 'prepaid'])){
            return redirect()->route('admin.publisher.profile');
        }
        return redirect()->route('admin.user.profile');

    }

    public function forgotPasswordForm(){
        if(Auth::check()){
            if( in_array(auth()->user()->team, ['media_buying', 'influencer', 'affiliate', 'prepaid'])){
                return redirect()->route('admin.publisher.profile');
            }
            return redirect()->route('admin.user.profile');
        }
        return view('new_admin.auth.forgot-password');
    }

    public function forgotPassword(Request $request){
        $request->validate([
            'email' => 'required|exists:users,email'
        ],[
            'email.exists' => 'This email dosn`t exists'
        ]);
        $code = rand(11111, 99999);
        Mail::to($request->email)->send(new ResetPassword($code));
        session(['reset_password_code' => $code, 'email' => $request->email]);
        return response()->json(true, 200);
        // return redirect()->route('admin.reset.password.form');
    }

    public function resetPasswordForm(){
        if(Auth::check()){
            if( in_array(auth()->user()->team, ['media_buying', 'influencer', 'affiliate', 'prepaid'])){
                return redirect()->route('admin.publisher.profile');
            }
            return redirect()->route('admin.user.profile');
        }
        return view('new_admin.auth.reset-password');
    }

    public function resetPassword(Request $request){

        if(session('reset_password_code') && session('email') && session('reset_password_code') == $request->code){
            $request->validate([
                'code' => 'required',
                'password' => ['required','confirmed', 'min:8']
            ]);

            $user = User::whereEmail(session('email'))->first();
            if(!$user){
                return redirect()->route('admin.forgot.password')->withErrors('This email dosne`t exists');
            }
            $user->password = Hash::make($request->password);
            $user->save();
            return redirect()->route('admin.login.form');
        }
        return redirect()->back()->withErrors('This code dosne`t corret');
    }




    /**
     * Log the user out of the application.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function logout(Request $request)
    {
        Auth::logout();
        $request->session()->invalidate();
        $request->session()->regenerateToken();
        return redirect()->route('admin.login');
    }
}

resources/views/publishers/coupons/load-payout.blade.php
<div class="table-responsive">
    <table class="table table-hover table-rounded table-striped border gy-7 gs-7">
        <thead>
            <tr class="fw-semibold fs-6 text-gray-800 border-bottom-2 border-gray-200">
                <th>Payout Type</th>
                <th>Payout</th>
                <th>New Payout</th>
                <th>Old Payout</th>
                <th>From Slab</th>
                <th>To Slab</th>
                <th>From Date</th>
                <th>To Date</th>
                <th>Countries</th>
            </tr>
        </thead>
        <tbody>
            {{-- @dd($coupon->cps->where('type', 'payout')) --}}
            @foreach ($coupon->cps->where('type', 'payout') as $payout)
                <tr>
                    <td>{{ $payout->amount_type }}</td>
                    <td>{{ $payout->amount }}</td>
                    <td>{{ $payout->new_amount }}</td>
                    <td>{{ $payout->old_amount }}</td>
                    <td>{{ $payout->from }}</td>
                    <td>{{ $payout->to }}</td>
                    <td>{{ $payout->from_date }}</td>
                    <td>{{ $payout->to_date }}</td>
                    <td>
                        @php($countryIds = json_decode($payout->countries_ids, true))
                        @if ($countryIds)
                            @foreach (json_decode($payout->countries_ids, true) as $countryId)
                                <span
                                    class="badge badge-light m-1">{{ App\Models\Country::where('id', $countryId)->first() ? App\Models\Country::where('id', $countryId)->first()->name_en : '' }}</span>
                            @endforeach
                        @endif
                    </td>
                </tr>
            @endforeach
        </tbody>
    </table>
</div>

resources/views/publishers/coupons/upload.blade.php
@extends('new_admin.layouts.app')
@section('title', 'Coupons')
@section('subtitle', 'Upload')
@section('content')

    <div class="toolbar mb-5 mb-lg-7" id="kt_toolbar">
        <!--begin::Page title-->
        <div class="page-title d-flex flex-column me-3">
            <!--begin::Title-->
            <h1 class="d-flex text-dark fw-bold my-1 fs-3">Upload Coupons</h1>
            <!--end::Title-->
            <!--begin::Breadcrumb-->
            <ul class="breadcrumb breadcrumb-dot fw-semibold text-gray-600 fs-7 my-1">
                <!--begin::Item-->
                <li class="breadcrumb-item text-gray-600">
                    <a href="{{ route('admin.index') }}" class="text-gray-600 text-hover-primary">Home</a>
                </li>
                <!--end::Item-->
                <!--begin::Item-->
                <li class="breadcrumb-item text-gray-600">Coupons</li>
                <!--end::Item-->
                <!--begin::Item-->
                <li class="breadcrumb-item text-gray-500">Upload</li>
                <!--end::Item-->
            </ul>
            <!--end::Breadcrumb-->
        </div>
        <!--end::Page title-->
    </div>

    <!--begin::Form-->
    <form id="kt_ecommerce_add_product_form" class="form d-flex flex-column flex-lg-row" action="{{route('admin.coupons.upload')}}" method="POST" enctype="multipart/form-data">
        @csrf
        <!--begin::Main column-->
        <div class="d-flex flex-column flex-row-fluid gap-7 gap-lg-10">

            <!--begin::Tab content-->
            <div class="tab-content">
                <!--begin::Tab pane-->
                <div class="tab-pane fade show active" id="kt_ecommerce_add_product_general" role="tab-panel">
                    <div class="d-flex flex-column gap-7 gap-lg-10">

                        <!--begin::General options-->
                        <div class="card card-flush py-4">
                            <!--begin::Card header-->
                            <div class="card-header">
                                <div class="card-title">
                                    <h2>General</h2>
                                </div>
                            </div>
                            <!--end::Card header-->
                            <!--begin::Card body-->
                            <div class="card-body pt-0">
                                <div class="row">

                                    <div class="col-md-4">
                                        <!--begin::Input group-->
                                        <div class="mb-10 fv-row">
                                            <!--begin::Label-->
                                            <label class="required form-label">Coupon Code</label>
                                            <!--end::Label-->
                                            <!--begin::Input-->
                                            <input type="file" name="coupons" class="form-control mb-2" placeholder="Coupon Code" value="{{ old('coupons') }}"   accept=".csv, application/vnd.openxmlformats-officedocument.spreadsheetml.sheet, application/vnd.ms-excel"/>
                                            @if ($errors->has('coupons'))
                                                <div class="fv-plugins-message-container invalid-feedback"><div data-field="text_input" >{{ $errors->first('coupons') }}</div></div>
                                            @endif
                                            <!--end::Input-->
                                        </div>
                                        <!--end::Input group-->
                                    </div>

                                    <div class="col-md-4">
                                        <!--begin::Input group-->
                                        <div class="mb-10 fv-row">
                                            <!--begin::Label-->
                                            <label class="form-label">Offer</label>
                                            <!--end::Label-->
                                            <!--begin::Input-->
                                            <select name="offer_id" data-control="select2" class="form-select">
                                                <option selected value="">{{ __('No one') }}</option>
                                                @foreach($offers as $offer)
                                                        <option {{old('offer_id')==$offer->id?"selected":""}} value="{{$offer->id}}">{{$offer->name}}</option>
                                                    @endforeach
                                            </select>
                                            <!--end::Input-->
                                            @if ($errors->has('offer_id'))
                                                <div class="fv-plugins-message-container invalid-feedback"><div data-field="text_input" >{{ $errors->first('offer_id') }}</div></div>
                                            @endif
                                        </div>
                                        <!--end::Input group-->
                                    </div>

                                    {{-- <div class="col-md-4">
                                        <!--begin::Input group-->
                                        <div class="mb-10 fv-row">
                                            <!--begin::Label-->
                                            <label class="form-label">Publisher</label>
                                            <!--end::Label-->
                                            <!--begin::Input-->
                                            <select name="team" data-control="select2" class="form-select">
                                                <option value="influencer">{{ __('Influencer') }}</option>
                                                <option value="affiliate">{{ __('Affiliate') }}</option>
                                                <option value="media_buying">{{ __('Media Buying') }}</option>
                                            </select>
                                            <!--end::Input-->
                                            @if ($errors->has('team'))
                                                <div class="fv-plugins-message-container invalid-feedback"><div data-field="text_input" >{{ $errors->first('team') }}</div></div>
                                            @endif
                                        </div>
                                        <!--end::Input group-->
                                    </div> --}}

                                    <div class="col-md-4">
                                        <br>
                                        <a href="{{ asset('dashboard/excel-sheets-examples/coupons.xlsx') }}" class="btn btn-primary mt-2" download>{{ __('Download Example') }}</a>
                                    </div>

                                </div>
                            </div>
                            <!--end::Card header-->
                        </div>
                        <!--end::General options-->
                    </div>
                </div>
                <!--end::Tab pane-->
            </div>
            <!--end::Tab content-->
            <div class="d-flex justify-content-end">
                <!--begin::Button-->
                <a href="{{ route('admin.coupons.index') }}" id="kt_ecommerce_add_product_cancel" class="btn btn-light me-5">Cancel</a>
                <!--end::Button-->
                <!--begin::Button-->
                <button type="submit" id="kt_ecommerce_add_product_submit" class="btn btn-primary">
                    <span class="indicator-label">Save Changes</span>
                    <span class="indicator-progress">Please wait...
                    <span class="spinner-border spinner-border-sm align-middle ms-2"></span></span>
                </button>
                <!--end::Button-->
                <button id="loading-button" class="btn btn-primary d-none" type="button" disabled>
                    <span class="spinner-border spinner-border-sm" role="status" aria-hidden="true"></span>
                    <span class="sr-only">Loading...</span>
                    Please wait...
                </button>
            </div>
        </div>
        <!--end::Main column-->
    </form>
    <!--end::Form-->
@endsection
@push('scripts')
    <script>let route = "{{ route('admin.coupons.index') }}";</script>
    <script>
        document.forms["kt_ecommerce_add_product_form"].addEventListener("submit", async (event) => {
            event.preventDefault();
            $("#loading-button").removeClass("d-none");
            $("#kt_ecommerce_add_product_submit").addClass("d-none")
            try {
                const resp = await fetch(event.target.action, {
                    method: "POST",
                    body: new FormData(event.target),
                });
                const body = await resp.json();
                console.log(body);
            }
            catch (e) {
                console.log(e);
            }
            window.location.href = route + '?uploading=true';
        });
    </script>
@endpush