routes/web.php
    Route::middleware(['auth:web','dashboard'])->group(function (){
        Route::get('index', 'DashboardController@index')->name('index');
        // Charts
        Route::get('charts/offers-analytics', 'DashboardController@chartOffersAnalytics')->name('chart.offers-analytics');
        Route::get('charts/gm-v-po', 'DashboardController@chartGmVPo')->name('chart.gm-v-po');

        Route::resource('users', UserController::class);
        Route::post('users/change/status', 'UserController@changeStatus');
        // User Profile
        Route::get('user/profile', 'UserController@profile')->name('user.profile');

        Route::resource('publishers', PublisherController::class);
        Route::get('publishers/type/{type}', 'PublisherController@getBasedOnType')->name('publishers.type');
        Route::get('publishers-search', 'PublisherController@search')->name('publishers.search');
        Route::post('publishers-update-account-manager', 'PublisherController@updateAccountManager')->name('publishers.updateAccountManager');
        Route::post('publishers-check-exists', 'PublisherController@checkIfExists')->name('publishers.check.exists');
        Route::post('publishers/change/status', 'PublisherController@changeStatus');
        Route::get('publishers/clear/sessions', 'PublisherController@clearFilterSeassoions')->name('publishers.clear.sessions');
        Route::get('publishers/files/download/{dir?}', 'PublisherController@download')->name('publishers.files.download');

        // Publisher Profile
        Route::get('publisher/profile/{id?}', 'PublisherController@profile')->name('publisher.profile');
        Route::get('publisher/payments/{id?}', 'PublisherController@payments')->name('publisher.payments');
        Route::get('publisher/my-account-manager', 'PublisherController@myAccountManager')->name('publisher.account.manager');

        // Upload Publishers
        Route::get('publishers/upload/form', 'PublisherController@upload')->name('publishers.upload.form');
        Route::post('publishers/upload', 'PublisherController@storeUpload')->name('publishers.upload.store');
        Route::get('publishers/import/status', 'PublisherController@importStatus')->name('publishers.import.status');

        // Upload update hasoffer id by email
        Route::get('publishers/upload/update-hasoffer-id-by-email/form', 'PublisherController@uploadUpdateHasOfferIdByEmail')->name('publishers.upload.update.hasoffer.id.by.email.form');
        Route::post('publishers/upload/update-hasoffer-id-by-email', 'PublisherController@storeUploadUpdateHasOfferIdByEmail')->name('publishers.upload.update.hasoffer.id.by.email.store');

        Route::resource('payments', PaymentController::class);
        Route::get('payments/upload/form', 'PaymentController@uploadForm')->name('payments.upload.form');
        Route::post('payments/upload/form', 'PaymentController@upload')->name('payments.upload');
        Route::get('payments/clear/sessions', 'PaymentController@clearFilterSeassoions')->name('payments.clear.sessions');

        Route::resource('roles', RoleController::class);
        Route::resource('cities', CityController::class);
        Route::resource('advertisers', AdvertiserController::class);
        Route::post('advertisers/change/status', 'AdvertiserController@changeStatus');

        Route::resource('categories', CategoryController::class);
        Route::resource('offers', OfferController::class);
        Route::get('my-offers', 'OfferController@myOffers')->name('my-offers');
        Route::get('upload/offers', 'OfferController@upload')->name('upload.offers');
        Route::get('offers/coupons/{offer}', 'OfferController@coupons')->name('offers.coupons');
        Route::get('offers/clear/sessions', 'OfferController@clearFilterSeassoions')->name('offers.clear.sessions');

        Route::resource('offerRequests', OfferRequestController::class);
        Route::get('ajax/offerRequests/form', 'OfferRequestController@offerRequestAjaxForm')->name('offerRequest.ajax.form');
        Route::post('ajax/offerRequests', 'OfferRequestController@offerRequestAjax')->name('offerRequest.ajax');
        Route::post('ajax/offerRequests/coupons', 'OfferRequestController@coupons')->name('offerRequest.ajax.coupons');
        Route::post('ajax/offerRequests/view-coupons', 'OfferRequestController@viewOfferCoupons')->name('offerRequest.ajax.view.coupons');
        Route::get('offerRequests/clear/sessions', 'OfferRequestController@clearFilterSeassoions')->name('offerRequests.clear.sessions');
        Route::post('offerRequests/change/status', 'OfferRequestController@changeStatus');

        Route::post('offers/change/status', 'OfferController@changeStatus');
        Route::get('coupons/bulk-edit', 'CouponController@bulkEdit')->name('coupons.bulk.edit');
        Route::post('coupons/bulk-update', 'CouponController@bulckUpdate')->name('coupons.bulk.update');
        Route::get('coupons/clear/sessions', 'CouponController@clearFilterSeassoions')->name('coupons.clear.sessions');
        Route::get('coupons/files/download/{dir?}', 'CouponController@download')->name('coupons.files.download');

        Route::get('trashed', 'TrashedController@index')->name('trashed.index');
        Route::put('trashed/restore', 'TrashedController@restore')->name('trashed.restore');

        Route::resource('helps', HelpController::class);
        Route::any('helps-upload-image', 'HelpController@uploadImages')->name('helps.image.upload');
        Route::post('helps-search', 'HelpController@search')->name('helps.search');
        // Route::get('help/{slug}', 'HelpController@showBySlug')->name('helps.show.by.slug');

        Route::resource('coupons', CouponController::class);
        Route::resource('reports', PivotReportController::class);
        Route::get('reports/import/status', 'PivotReportController@status')->name('reports.import.status');

        Route::get('reports/clear/sessions', 'PivotReportController@clearFilterSeassoions')->name('reports.clear.sessions');
        //todo
        //        Route::get('publishers/files/download/{dir?}', 'PublisherController@download')->name('publishers.files.download');
        Route::get('reports/download/errors/{dir?}', 'PivotReportController@downLoadErrors')->name('reports.deonload.errore');
        Route::get('reports/define/excel/sheet/columns', 'PivotReportController@defineExcelSheetColumns')->name('define.excel.sheet.columns');
        Route::get('coupons/upload/form', 'CouponController@uploadForm')->name('coupons.upload.form');
        Route::post('coupons/upload','CouponController@upload')->name('coupons.upload');
        Route::get('coupons/upload/status', 'CouponController@importStatus')->name('coupons.upload.status');
        Route::post('coupons/change/status', 'CouponController@changeStatus');
        Route::post('coupons/change/revenue', 'CouponController@bulkChangeRevenue');
        Route::get('coupons/load/payout', 'CouponController@loadPayout');

        // Route::resource('reports', ReportController::class);
        Route::resource('countries', CountryController::class);
        Route::resource('cities', CityController::class);
        Route::resource('targets', TargetController::class);
        // User Activites
        Route::get('user-activities', 'UserActivityController@index')->name('user.activities.index');
        Route::post('user-activities/update-uproval', 'UserActivityController@updateUserActivityApproval')->name('user.activities.update.approval');
        // Chat routes
        Route::get('chat', 'ChatController@index')->name('chat');
        Route::post('chat/message', 'ChatController@messageReceived')->name('chat.message');
        Route::post('chat/single/{user?}', 'ChatController@singleChat')->name('chat.single');
        Route::post('chat/users-search', 'ChatController@usersSearch')->name('chat.users.search');

        Route::group([
            'excluded_middleware' => ['dashboard'],
        ], function () {
            Route::post('logout', 'AuthController@logout')->name('logout');
        });

        // Ajax requests
        Route::post('ajax/cities', 'AjaxController@cities')->name('ajax.cities');
        Route::post('ajax/account-managers', 'AjaxController@accountManagers')->name('ajax.account.managers');
        Route::post('ajax/view-activity-history', 'AjaxController@viewActivityHistory')->name('ajax.view.activity.history');
        Route::post('ajax/read-notification', 'AjaxController@readNotifications')->name('ajax.read.notifications');
        Route::get('ajax/publishers/search', 'AjaxController@publishersSearch')->name('ajax.publishers.search');
        Route::get('ajax/check/jobs', 'AjaxController@checkJobs')->name('ajax.check.jobs');
        // Delete this routes and views
        Route::group(['prefix' => 'publisher'], function(){
            Route::get('dashboard', 'PublisherController@dashboard')->name('publisher.dashboard');
            Route::get('offers', 'PublisherController@offers')->name('publisher.offers');
        });

        Route::group(['prefix' => 'table-handler', 'as' => 'table.handler.'], function(){
            Route::get('set-table-length', 'TableHandlerController@setTableLength')->name('set.table.length');
            Route::get('offers', 'PublisherController@offers')->name('publisher.offers');
        });
    });
});

// Salla Routes
Route::group(['prefix' => 'salla', 'namespace' => 'Dashboard', 'as' => 'salla.'], function(){
    Route::get('install', 'SallaInfoController@installApp');
    Route::view('success', 'admin.salla.install-success')->name('installed.successfully');
    Route::view('failed', 'admin.salla.install-failed')->name('installed.failed');
});

Route::get('login-users', 'Dashboard\DashboardController@loginUsers')->name('login.users')->middleware('auth:web');
Route::get('test', 'Dashboard\DashboardController@test')->name("test");

Route::get('/optimize', function () {
    Artisan::call('optimize:clear');
    Artisan::call('config:clear');

app/Models/Category.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsToMany;
use Illuminate\Database\Eloquent\SoftDeletes;

/**
 * @method static select(string $string)
 */
class Category extends Model
{
    use SoftDeletes;
    use HasFactory;
    protected $guarded = [];
    protected $appends = ['title'];

    public function getTitleAttribute(){
        return $this->attributes['title_'.app()->getLocale()];
    }

    public function offers(): BelongsToMany
    {
        return $this->BelongsToMany(Offer::class);
    }
}

app/Http/Controllers/Dashboard/CategoryController.php
<?php


namespace App\Http\Controllers\Dashboard;

use App\Http\Controllers\Controller;
use App\Models\Category;
use Illuminate\Http\Request;
use Yajra\DataTables\Facades\DataTables;

class CategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $this->authorize('view_categories');
        if($request->ajax()){
            // $categories = getModelData('Category' , $request);
            // return response()->json($categories);

            $categories = Category::all();
            return DataTables::of($categories)->make(true);
        }
        return view('new_admin.categories.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $this->authorize('create_categories');
        return view('new_admin.categories.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->authorize('create_categories');
        $data = $request->validate([
            'title_en' => 'required|max:255',
            'title_ar' => 'required|max:255',
            'type'     => 'required|in:affiliate,influencer,advertisers,offers,other'
        ]);

        $category = Category::create($data);
        userActivity('Category', $category->id, 'create');

        $notification = [
            'message' => 'Created successfully',
            'alert-type' => 'success'
        ];
        return redirect()->route('admin.categories.index')->with($notification);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        abort(404);
        $this->authorize('view_categories');
        $category = Category::findOrFail($id);
        userActivity('Category', $category->id, 'show');
        return view('admin.categories.show', ['category' => $category]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Category $category)
    {
        $this->authorize('view_categories');
        return view('new_admin.categories.edit', [
            'category' => $category
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Category $category)
    {
        $this->authorize('update_categories');
        $data = $request->validate([
            'title_ar' => 'required|max:255',
            'title_en' => 'required|max:255',
            'type'     => 'required|in:affiliate,influencer,advertisers,offers,other'
        ]);
        userActivity('Category', $category->id, 'update', $data, $category);

        $category->update($data);

        $notification = [
            'message' => 'Updated successfully',
            'alert-type' => 'success'
        ];
        return redirect()->route('admin.categories.index')->with($notification);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Request $request, Category $category)
    {
        $this->authorize('delete_categories');
        if($request->ajax()){
            userActivity('Category', $category->id, 'delete');
            $category->forceDelete();
        }
    }
}

resources/views/admin/categories/create.blade.php
@extends('admin.layouts.app')
@section('title','Categories')
@section('content')
    <!--begin::Entry-->
    <div class="d-flex flex-column-fluid">
        <!--begin::Container-->
        <div class="container">
            <!--begin::Card-->
            <div class="row">
                <div class="col-lg-12">
                    <div class="card card-custom example example-compact">
                        <div class="card-header">
                            <h2 class="card-title">{{ __('Create New Category') }}</h2>
                        </div>
                        <!--begin::Form-->
                        <form class="form" id="kt_form" action="{{route('admin.categories.store')}}" method = "POST" enctype="multipart/form-data">
                            @csrf
                            <div class="card-body">
                                @if ($errors->any())
                                <div class="alert alert-custom alert-light-danger" role="alert" id="kt_form_2_msg" >
                                    <div class="alert-icon">
                                        <i class="flaticon2-bell-5"></i>
                                    </div>
                                    <div class="alert-text font-weight-bold">{{ __('Validation error') }}</div>
                                    <ul>
                                        @foreach ($errors->all() as $error)
                                            <li>{{ $error }}</li>
                                        @endforeach
                                    </ul>
                                    <div class="alert-close">
                                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                            <span>
                                                <i class="ki ki-close"></i>
                                            </span>
                                    </button>
                                    </div>
                                </div>
                                @endif
                                <div class="mb-3">
                                    <div class="mb-2">
                                        <div class="form-group row">
                                            <div class="col-lg-4">
                                                <label>* اسم القسم باللغه العربية :</label>
                                                <input type="text" name="title_ar" class="form-control"  value="{{old('title_ar')}}" required />
                                                @if ($errors->has('title_ar'))
                                                    <div>
                                                        <p class="invalid-input">{{ $errors->first('title_ar') }}</p>
                                                    </div>
                                                @endif
                                            </div>
                                            <div class="col-lg-4">
                                                <label>* Category Title In English :</label>
                                                <input type="text" name="title_en" class="form-control"  value="{{old('title_en')}}" required />
                                                @if ($errors->has('title_en'))
                                                    <div>
                                                        <p class="invalid-input">{{ $errors->first('title_en') }}</p>
                                                    </div>
                                                @endif
                                            </div>
                                            <div class="col-lg-4">
                                                <label>* {{ __('Category Type') }} :</label>
                                                <select class="form-control select2" id="kt_select_type" name="type" >
                                                    <option {{ old('type')=="affiliate"?"selected":"" }} value="affiliate">{{ __('Affiliate') }}</option>
                                                    <option {{ old('type')=="influencer"?"selected":"" }} value="influencer">{{ __('Influencer') }}</option>
                                                    <option {{ old('type')=="advertisers"?"selected":"" }} value="advertisers">{{ __('Advertisers') }}</option>
                                                    <option {{ old('type')=="offers"?"selected":"" }} value="offers">{{ __('Offers') }}</option>
                                                    <option {{ old('type')=="other"?"selected":"" }} value="other">{{ __('Other') }}</option>
                                                </select>
                                                @if ($errors->has('type'))
                                                    <div>
                                                        <p class="invalid-input">{{ $errors->first('type') }}</p>
                                                    </div>
                                                @endif
                                            </div>
                                        </div>

                                    </div>
                                </div>
                            </div>
                            <div class="card-footer">
                                <div class="row">
                                    <div class="col-lg-12 text-center">
                                        <button type="reset" class="btn btn-light-primary font-weight-bold">{{ __('Cancel') }}</button>
                                        <button type="submit" class="btn btn-primary font-weight-bold mr-2">{{ __("Submit") }}</button>
                                    </div>
                                </div>
                            </div>
                        </form>
                        <!--end::Form-->
                    </div>
                    <!--end::Card-->
                </div>
            </div>
        </div>
        <!--end::Container-->
    </div>
    <!--end::Entry-->
@endsection
@push('scripts')
   <script>
       $('#kt_select_type').select2({
            placeholder: "Select Option",
        });
    </script> 
@endpush

resources/views/admin/categories/edit.blade.php
@extends('admin.layouts.app')
@section('title','Category')
@section('content')
    <!--begin::Entry-->
    <div class="d-flex flex-column-fluid">
        <!--begin::Container-->
        <div class="container">

            <!--begin::Card-->
            <div class="row">
                <div class="col-lg-12">
                    <div class="card card-custom example example-compact">
                        <div class="card-header">
                            <h2 class="card-title"> {{ __('Category') }} {{ $category->title }}</h2>
                        </div>
                        <!--begin::Form-->
                        <form class="form" id="kt_form" action="{{route('admin.categories.update',$category->id)}}" method = "POST" enctype="multipart/form-data">
                            @csrf
                            @method('PUT')
                            
                            <div class="card-body">
                                @if ($errors->any())
                                    <div class="alert alert-custom alert-light-danger" role="alert" id="kt_form_2_msg" >
                                        <div class="alert-icon">
                                            <i class="flaticon2-bell-5"></i>
                                        </div>
                                        <div class="alert-text font-weight-bold">{{ __('Validation error') }}</div>
                                        <ul>
                                            @foreach($errors->all() as $error )
                                                <li>{{$error}}</li>
                                            @endforeach
                                        </ul>
                                        <div class="alert-close">
                                            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                            <span>
                                                <i class="ki ki-close"></i>
                                            </span>
                                            </button>
                                        </div>
                                    </div>
                                @endif
                                <div class="mb-3">
                                    <div class="mb-2">
                                        <div class="form-group row">
                                            <div class="col-lg-4">
                                                <label>* اسم القسم باللغة العربية :</label>
                                                <input type="text" name="title_ar" class="form-control"  value="{{old('title_ar') ?? $category->title_ar}}" />
                                                @if ($errors->has('title_ar'))
                                                    <div>
                                                        <p class="invalid-input">{{ $errors->first('title_ar') }}</p>
                                                    </div>
                                                @endif
                                            </div>    
                                            <div class="col-lg-4">
                                                <label>* Category Name In English :</label>
                                                <input type="text" name="title_en" class="form-control"  value="{{old('title_en') ?? $category->title_en}}" />
                                                @if ($errors->has('title_en'))
                                                    <div>
                                                        <p class="invalid-input">{{ $errors->first('title_en') }}</p>
                                                    </div>
                                                @endif
                                            </div>  
                                            <div class="col-lg-4">
                                                <label>* {{ __('Category Type') }} :</label>
                                                <select class="form-control select2" id="kt_select_type" name="type" >
                                                    <option {{ old('type')=="affiliate"?"selected":($category->type=='affiliate'?"selected":'') }} value="affiliate">{{ __('Affiliate') }}</option>
                                                    <option {{ old('type')=="influencer"?"selected":($category->type=='influencer'?"selected":'') }} value="influencer">{{ __('Influencer') }}</option>
                                                    <option {{ old('type')=="advertisers"?"selected":($category->type=='advertisers'?"selected":'') }} value="advertisers">{{ __('Advertisers') }}</option>
                                                    <option {{ old('type')=="offers"?"selected":($category->type=='offers'?"selected":'') }} value="offers">{{ __('Offers') }}</option>
                                                    <option {{ old('type')=="other"?"selected":($category->type=='other'?"selected":'') }} value="other">{{ __('Other') }}</option>
                                                </select>
                                                @if ($errors->has('type'))
                                                    <div>
                                                        <p class="invalid-input">{{ $errors->first('type') }}</p>
                                                    </div>
                                                @endif
                                            </div> 
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="card-footer">
                                <div class="row">
                                    <div class="col-lg-12 text-center">
                                        <button type="reset" class="btn btn-light-primary font-weight-bold">{{ _('Cancel') }}</button>
                                        <button type="submit" class="btn btn-primary font-weight-bold mr-2">{{ _('Submit') }}</button>
                                    </div>
                                </div>
                            </div>
                        </form>
                        <!--end::Form-->
                    </div>
                    <!--end::Card-->
                </div>
            </div>
        </div>
        <!--end::Container-->
    </div>
    <!--end::Entry-->
@endsection
@push('scripts')
   <script>
       $('#kt_select_type').select2({
            placeholder: "Select Option",
        });
    </script> 
@endpush